# See https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
_extends: jenkinsci/.github
# Required for https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildDockerAndPublishImage.groovy
name-template: 'next'
tag-template: 'next'
